package com.chris.uberratebanner;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.*;import android.text.*;import android.text.style.ForegroundColorSpan;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class HistoryActivity extends Activity{
 private RideDatabase db;private LinearLayout listHost,kpiHost;private DonutView donut;private TextView filterBtn,sortBtn;private String filter="All";private long customStart=0,customEnd=Long.MAX_VALUE;private boolean group=true;private int sortMode=0;private final Set<String> collapsed=new HashSet<>();private List<RideRecord> visible=new ArrayList<>();
 @Override protected void onCreate(Bundle b){super.onCreate(b);UiKit.applySystemBars(this);db=new RideDatabase(this);build();}
 private void build(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(UiKit.BG);UiKit.applySafeInsets(shell,0,0,0,0);ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(10),dp(16),dp(18));sv.addView(root);shell.addView(sv,new LinearLayout.LayoutParams(-1,0,1));shell.addView(UiKit.bottomNav(this,1));setContentView(shell);root.addView(UiKit.text(this,"Ride History",24,true));LinearLayout tools=new LinearLayout(this);tools.setOrientation(LinearLayout.HORIZONTAL);filterBtn=UiKit.compactToolButton(this,"▾","Date",v->chooseFilter());sortBtn=UiKit.compactToolButton(this,"⇅","Sort",v->chooseSort());TextView del=UiKit.compactToolButton(this,"⌫","Delete",v->deleteMenu());TextView csv=UiKit.compactToolButton(this,"⇩","CSV",v->exportCsv());TextView[] toolViews=new TextView[]{filterBtn,sortBtn,del,csv};for(int i=0;i<toolViews.length;i++){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(54),1);lp.leftMargin=i==0?0:dp(4);lp.rightMargin=i==toolViews.length-1?0:dp(4);tools.addView(toolViews[i],lp);}root.addView(tools,top(10));kpiHost=new LinearLayout(this);kpiHost.setOrientation(LinearLayout.VERTICAL);root.addView(kpiHost,top(12));listHost=new LinearLayout(this);listHost.setOrientation(LinearLayout.VERTICAL);root.addView(listHost,top(10));}
 @Override protected void onResume(){super.onResume();refresh();}
 private void refresh(){visible=filtered(db.getAll());renderKpis();renderList();UiKit.setCompactToolLabel(filterBtn,"▾",filter);}
 private List<RideRecord> filtered(List<RideRecord> all){long now=System.currentTimeMillis(),start=0,end=Long.MAX_VALUE;Calendar c=Calendar.getInstance();if(filter.equals("Today")){zero(c);start=c.getTimeInMillis();end=start+86400000L;}else if(filter.equals("Yesterday")){zero(c);end=c.getTimeInMillis();start=end-86400000L;}else if(filter.equals("7 Days"))start=now-7L*86400000L;else if(filter.equals("30 Days"))start=now-30L*86400000L;else if(filter.equals("Custom")){start=customStart;end=customEnd;}List<RideRecord> o=new ArrayList<>();for(RideRecord r:all)if(r.createdAt>=start&&r.createdAt<end)o.add(r);Comparator<RideRecord> cmp;if(sortMode==1)cmp=Comparator.comparingLong(r->r.createdAt);else if(sortMode==2)cmp=(a,b)->Double.compare(b.hourly,a.hourly);else if(sortMode==3)cmp=Comparator.comparingDouble(r->r.hourly);else cmp=(a,b)->Long.compare(b.createdAt,a.createdAt);o.sort(cmp);return o;}
 private void renderKpis(){kpiHost.removeAllViews();LinearLayout card=card();LinearLayout metrics=new LinearLayout(this);metrics.setOrientation(LinearLayout.HORIZONTAL);double avgRate=0,avgPay=0,avgTime=0;int lo=0,mid=0,hi=0;for(RideRecord r:visible){avgRate+=r.hourly;avgPay+=r.payout;avgTime+=r.totalMinutes;int x=RateColors.rangeFor(this,r.hourly);if(x==0)lo++;else if(x==1)mid++;else hi++;}int n=visible.size();if(n>0){avgRate/=n;avgPay/=n;avgTime/=n;}metrics.addView(kpi("Offers",String.valueOf(n)),new LinearLayout.LayoutParams(0,-2,1));metrics.addView(kpi("Avg $/hr",String.format(Locale.US,"$%.2f",avgRate)),new LinearLayout.LayoutParams(0,-2,1));metrics.addView(kpi("Avg offer",String.format(Locale.US,"$%.2f",avgPay)),new LinearLayout.LayoutParams(0,-2,1));metrics.addView(kpi("Avg time",String.format(Locale.US,"%.0f min",avgTime)),new LinearLayout.LayoutParams(0,-2,1));card.addView(metrics);donut=new DonutView(this);donut.setData(lo,mid,hi,AppSettings.bottomBannerColor(this),AppSettings.midBannerColor(this),AppSettings.topBannerColor(this));card.addView(donut,new LinearLayout.LayoutParams(-1,dp(120)));TextView legend=UiKit.muted(this,"Bottom "+lo+"   •   Mid "+mid+"   •   Top "+hi,12);legend.setGravity(Gravity.CENTER);card.addView(legend);kpiHost.addView(card);}
 private void renderList(){listHost.removeAllViews();if(visible.isEmpty()){listHost.addView(UiKit.muted(this,"No offers in this date range.",14));return;}if(!group){for(RideRecord r:visible)addRide(r,listHost);return;}SimpleDateFormat key=new SimpleDateFormat("yyyy-MM-dd",Locale.US),lab=new SimpleDateFormat("EEEE M/d/yyyy",Locale.US);LinkedHashMap<String,List<RideRecord>> map=new LinkedHashMap<>();for(RideRecord r:visible)map.computeIfAbsent(key.format(new Date(r.createdAt)),x->new ArrayList<>()).add(r);for(Map.Entry<String,List<RideRecord>> e:map.entrySet()){String k=e.getKey();boolean col=collapsed.contains(k);TextView h=UiKit.text(this,lab.format(new Date(e.getValue().get(0).createdAt))+(col?"  ▸":"  ▾"),15,true);h.setPadding(dp(4),dp(12),dp(4),dp(8));h.setOnClickListener(v->{if(collapsed.contains(k))collapsed.remove(k);else collapsed.add(k);renderList();});listHost.addView(h);if(!col)for(RideRecord r:e.getValue())addRide(r,listHost);}}
 private void addRide(RideRecord r,LinearLayout parent){String s=String.format(Locale.US,"Rate: $%.2f/hr | Offer $%.2f / %d min",r.hourly,r.payout,r.totalMinutes);SpannableString sp=new SpannableString(s);int end=s.indexOf(" | ");sp.setSpan(new ForegroundColorSpan(RateColors.forHourly(this,r.hourly)),0,end,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);sp.setSpan(new android.text.style.StyleSpan(Typeface.BOLD),0,end,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);TextView row=UiKit.text(this,"",14,false);row.setText(sp);row.setMaxLines(3);row.setPadding(dp(13),dp(12),dp(13),dp(12));row.setBackground(UiKit.rounded(UiKit.SURFACE,11,this));row.setOnClickListener(v->{Intent i=new Intent(this,RideDetailActivity.class);i.putExtra("ride_id",r.id);startActivity(i);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(7);parent.addView(row,p);}
 private LinearLayout kpi(String a,String b){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.addView(UiKit.muted(this,a,10));TextView v=UiKit.text(this,b,14,true);v.setGravity(Gravity.CENTER);x.addView(v);return x;}private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(10),dp(12),dp(10),dp(12));c.setBackground(UiKit.rounded(UiKit.SURFACE,12,this));return c;}
 private void chooseFilter(){String[] a={"Today","Yesterday","7 Days","30 Days","All","Custom"};new AlertDialog.Builder(this).setTitle("Date filter").setItems(a,(d,w)->{filter=a[w];if(filter.equals("Custom"))pickCustom();else refresh();}).show();}
 private void pickCustom(){Calendar c=Calendar.getInstance();new DatePickerDialog(this,(v,y,m,day)->{Calendar s=Calendar.getInstance();s.set(y,m,day,0,0,0);s.set(Calendar.MILLISECOND,0);customStart=s.getTimeInMillis();new DatePickerDialog(this,(v2,y2,m2,d2)->{Calendar e=Calendar.getInstance();e.set(y2,m2,d2,0,0,0);e.set(Calendar.MILLISECOND,0);customEnd=e.getTimeInMillis()+86400000L;refresh();},y,m,day).show();},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
 private void chooseSort(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);Switch g=new Switch(this);g.setText("Group by date");g.setChecked(group);g.setTextColor(UiKit.TEXT);box.addView(g);String[] a={"Newest → Oldest","Oldest → Newest","Highest rate → Lowest","Lowest rate → Highest"};Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));s.setSelection(sortMode);box.addView(s);new AlertDialog.Builder(this).setTitle("Sort history").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{group=g.isChecked();sortMode=s.getSelectedItemPosition();refresh();}).show();}
 private void deleteMenu(){String[] a={"Select individual offers","Select entire days","Clear all"};new AlertDialog.Builder(this).setTitle("Delete").setItems(a,(d,w)->{if(w==0)deleteOffers();else if(w==1)deleteDays();else new AlertDialog.Builder(this).setTitle("Clear all history?").setNegativeButton("Cancel",null).setPositiveButton("Clear all",(x,y)->{db.clearAll();refresh();}).show();}).show();}
 private void deleteOffers(){String[] labels=new String[visible.size()];boolean[] ck=new boolean[visible.size()];for(int i=0;i<visible.size();i++){RideRecord r=visible.get(i);labels[i]=String.format(Locale.US,"$%.2f/hr | $%.2f / %d min",r.hourly,r.payout,r.totalMinutes);}new AlertDialog.Builder(this).setTitle("Select offers").setMultiChoiceItems(labels,ck,(d,w,c)->ck[w]=c).setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{List<Long> ids=new ArrayList<>();for(int i=0;i<ck.length;i++)if(ck[i])ids.add(visible.get(i).id);db.deleteMany(ids);refresh();}).show();}
 private void deleteDays(){SimpleDateFormat k=new SimpleDateFormat("yyyy-MM-dd",Locale.US),l=new SimpleDateFormat("EEEE M/d/yyyy",Locale.US);LinkedHashMap<String,List<Long>> m=new LinkedHashMap<>();LinkedHashMap<String,String> labs=new LinkedHashMap<>();for(RideRecord r:visible){String x=k.format(new Date(r.createdAt));m.computeIfAbsent(x,z->new ArrayList<>()).add(r.id);labs.put(x,l.format(new Date(r.createdAt)));}String[] keys=m.keySet().toArray(new String[0]),labels=new String[keys.length];boolean[] ck=new boolean[keys.length];for(int i=0;i<keys.length;i++)labels[i]=labs.get(keys[i]);new AlertDialog.Builder(this).setTitle("Select days").setMultiChoiceItems(labels,ck,(d,w,c)->ck[w]=c).setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{List<Long> ids=new ArrayList<>();for(int i=0;i<ck.length;i++)if(ck[i])ids.addAll(m.get(keys[i]));db.deleteMany(ids);refresh();}).show();}
 private void exportCsv(){try{SimpleDateFormat df=new SimpleDateFormat("MM/dd/yyyy",Locale.getDefault()),tf=new SimpleDateFormat("h:mm a",Locale.getDefault());StringBuilder s=new StringBuilder("Date,Time,Type,Offer $,Total time\n");for(RideRecord r:visible)s.append(df.format(new Date(r.createdAt))).append(',').append(tf.format(new Date(r.createdAt))).append(',').append(r.type).append(',').append(String.format(Locale.US,"%.2f",r.payout)).append(',').append(r.totalMinutes).append('\n');ImageStorage.writeCsv(this,"RideRate_History_"+System.currentTimeMillis()+".csv",s.toString());Toast.makeText(this,"CSV saved to Downloads/RideRate",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"CSV export failed",Toast.LENGTH_LONG).show();}}
 private void zero(Calendar c){c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);}private int dp(int v){return UiKit.dp(this,v);}private LinearLayout.LayoutParams top(int t){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(t);return p;}@Override protected void onDestroy(){db.close();super.onDestroy();}
}
