package com.chris.uberratebanner;
import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import java.io.*;import java.text.*;import java.util.*;
public final class ImageStorage{
 private ImageStorage(){}
 public static String saveVerificationCrop(Context c,Bitmap src,Rect crop,long key)throws Exception{Bitmap b=make(src,crop);File d=new File(c.getFilesDir(),"ride_thumbs");if(!d.exists())d.mkdirs();File f=new File(d,"ride_"+key+".jpg");try(FileOutputStream o=new FileOutputStream(f)){b.compress(Bitmap.CompressFormat.JPEG,84,o);}b.recycle();return f.getAbsolutePath();}
 public static void deletePrivate(String p){if(p!=null)try{new File(p).delete();}catch(Exception ignored){}}
 public static Uri downloadRideSnapshot(Context c,RideRecord r)throws Exception{if(r.thumbPath==null)throw new IOException("No captured image is available.");Bitmap src=BitmapFactory.decodeFile(r.thumbPath);if(src==null)throw new IOException("Captured image could not be opened.");int bar=Math.max(72,Math.round(src.getWidth()*0.12f));Bitmap out=Bitmap.createBitmap(src.getWidth(),src.getHeight()+bar,Bitmap.Config.ARGB_8888);Canvas cv=new Canvas(out);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);int color=RateColors.forHourly(c,r.hourly);p.setColor(withAlpha(color,204));cv.drawRect(0,0,out.getWidth(),bar,p);p.setColor(RateColors.textForHourly(c,r.hourly));p.setTextSize(bar*.38f);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextAlign(Paint.Align.CENTER);cv.drawText(String.format(Locale.US,"$%.2f/hr  •  $%.2f  •  %d min",r.hourly,r.payout,r.totalMinutes),out.getWidth()/2f,bar*.64f,p);cv.drawBitmap(src,0,bar,null);src.recycle();String stamp=new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date(r.createdAt));Uri uri=writeDownload(c,"RideRate_"+stamp+".jpg","image/jpeg",out);out.recycle();return uri;}
 public static Uri writeCsv(Context c,String name,String csv)throws Exception{return writeBytes(c,name,"text/csv",csv.getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 private static Uri writeDownload(Context c,String name,String mime,Bitmap b)throws Exception{ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,name);v.put(MediaStore.Downloads.MIME_TYPE,mime);if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/RideRate");Uri u=c.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("Could not create download");try(OutputStream o=c.getContentResolver().openOutputStream(u)){if(o==null)throw new IOException("Download stream unavailable");b.compress(Bitmap.CompressFormat.JPEG,88,o);}return u;}
 private static Uri writeBytes(Context c,String name,String mime,byte[] data)throws Exception{ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,name);v.put(MediaStore.Downloads.MIME_TYPE,mime);if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/RideRate");Uri u=c.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("Could not create download");try(OutputStream o=c.getContentResolver().openOutputStream(u)){o.write(data);}return u;}
 private static Bitmap make(Bitmap s,Rect crop){Rect r=sanitizeCrop(s,crop);Bitmap b=Bitmap.createBitmap(s,r.left,r.top,r.width(),r.height());if(b.getWidth()>1080){int h=Math.max(1,Math.round(b.getHeight()*1080f/b.getWidth()));Bitmap z=Bitmap.createScaledBitmap(b,1080,h,true);b.recycle();b=z;}return b;}
 public static Rect sanitizeCrop(Bitmap b,Rect crop){int w=b.getWidth(),h=b.getHeight();if(crop==null||crop.width()<=0||crop.height()<=0)return new Rect(0,0,w,h);int pad=Math.max(70,Math.round(crop.height()*.55f));int top=Math.max(0,crop.top-pad),bot=Math.min(h,crop.bottom+pad);return new Rect(0,top,w,bot);}
 private static int withAlpha(int c,int a){return Color.argb(a,Color.red(c),Color.green(c),Color.blue(c));}
}
