package com.chris.uberratebanner;
import android.content.*;import android.database.*;import android.database.sqlite.*;import java.util.*;
public class RideDatabase extends SQLiteOpenHelper{
 private static final String DB_NAME="ride_rate.db"; private static final int DB_VERSION=4; private final Context app;
 public RideDatabase(Context c){super(c,DB_NAME,null,DB_VERSION);app=c.getApplicationContext();}
 @Override public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE rides (id INTEGER PRIMARY KEY AUTOINCREMENT,created_at INTEGER NOT NULL,payout REAL NOT NULL,pickup_min INTEGER NOT NULL,trip_min INTEGER NOT NULL,total_min INTEGER NOT NULL,base_total_min INTEGER NOT NULL DEFAULT 0,delivery_buffer_min INTEGER NOT NULL DEFAULT 0,stop_count INTEGER NOT NULL DEFAULT 0,stop_buffer_min INTEGER NOT NULL DEFAULT 0,hourly REAL NOT NULL,type TEXT NOT NULL DEFAULT 'Ride',source TEXT NOT NULL,thumb_path TEXT,ocr_text TEXT,archived INTEGER NOT NULL DEFAULT 0)");db.execSQL("CREATE INDEX idx_rides_time ON rides(created_at)");}
 @Override public void onUpgrade(SQLiteDatabase db,int oldV,int newV){
  if(oldV<3){try{db.execSQL("ALTER TABLE rides ADD COLUMN base_total_min INTEGER NOT NULL DEFAULT 0");}catch(Exception ignored){}try{db.execSQL("ALTER TABLE rides ADD COLUMN delivery_buffer_min INTEGER NOT NULL DEFAULT 0");}catch(Exception ignored){}try{db.execSQL("ALTER TABLE rides ADD COLUMN type TEXT NOT NULL DEFAULT 'Ride'");}catch(Exception ignored){}}
  if(oldV<4){try{db.execSQL("ALTER TABLE rides ADD COLUMN stop_count INTEGER NOT NULL DEFAULT 0");}catch(Exception ignored){}try{db.execSQL("ALTER TABLE rides ADD COLUMN stop_buffer_min INTEGER NOT NULL DEFAULT 0");}catch(Exception ignored){}}
 }
 public long insert(RideRecord r){ContentValues v=vals(r);long id=getWritableDatabase().insertOrThrow("rides",null,v);enforceRetention();return id;}
 public void updateThumb(long id,String p){ContentValues v=new ContentValues();v.put("thumb_path",p);getWritableDatabase().update("rides",v,"id=?",new String[]{""+id});}
 public RideRecord get(long id){Cursor c=getReadableDatabase().query("rides",null,"id=?",new String[]{""+id},null,null,null);try{return c.moveToFirst()?from(c):null;}finally{c.close();}}
 public List<RideRecord> getAll(){List<RideRecord> o=new ArrayList<>();Cursor c=getReadableDatabase().query("rides",null,null,null,null,null,"created_at DESC");try{while(c.moveToNext())o.add(from(c));}finally{c.close();}return o;}
 public void setArchived(long id,boolean a){ContentValues v=new ContentValues();v.put("archived",a?1:0);getWritableDatabase().update("rides",v,"id=?",new String[]{""+id});if(!a)enforceRetention();}
 public void delete(long id){RideRecord r=get(id);getWritableDatabase().delete("rides","id=?",new String[]{""+id});if(r!=null)ImageStorage.deletePrivate(r.thumbPath);}
 public void deleteMany(Collection<Long> ids){for(Long id:ids)delete(id);}
 public void clearAll(){for(RideRecord r:getAll())delete(r.id);}
 public void enforceRetention(){if(!AppSettings.autoDeleteEnabled(app))return;int lim=AppSettings.historyLimit(app);List<RideRecord> normal=new ArrayList<>();for(RideRecord r:getAll())if(!r.archived)normal.add(r);for(int i=lim;i<normal.size();i++)delete(normal.get(i).id);}
 private ContentValues vals(RideRecord r){ContentValues v=new ContentValues();v.put("created_at",r.createdAt);v.put("payout",r.payout);v.put("pickup_min",r.pickupMinutes);v.put("trip_min",r.tripMinutes);v.put("total_min",r.totalMinutes);v.put("base_total_min",r.baseTotalMinutes);v.put("delivery_buffer_min",r.deliveryBufferMinutes);v.put("stop_count",r.stopCount);v.put("stop_buffer_min",r.stopBufferMinutes);v.put("hourly",r.hourly);v.put("type",r.type==null?"Ride":r.type);v.put("source",r.source==null?"Unknown":r.source);if(r.thumbPath!=null)v.put("thumb_path",r.thumbPath);if(r.ocrText!=null)v.put("ocr_text",r.ocrText);v.put("archived",r.archived?1:0);return v;}
 private RideRecord from(Cursor c){RideRecord r=new RideRecord();r.id=c.getLong(c.getColumnIndexOrThrow("id"));r.createdAt=c.getLong(c.getColumnIndexOrThrow("created_at"));r.payout=c.getDouble(c.getColumnIndexOrThrow("payout"));r.pickupMinutes=c.getInt(c.getColumnIndexOrThrow("pickup_min"));r.tripMinutes=c.getInt(c.getColumnIndexOrThrow("trip_min"));r.totalMinutes=c.getInt(c.getColumnIndexOrThrow("total_min"));int x=c.getColumnIndex("base_total_min");r.baseTotalMinutes=x>=0?c.getInt(x):r.totalMinutes;x=c.getColumnIndex("delivery_buffer_min");r.deliveryBufferMinutes=x>=0?c.getInt(x):0;x=c.getColumnIndex("stop_count");r.stopCount=x>=0?c.getInt(x):0;x=c.getColumnIndex("stop_buffer_min");r.stopBufferMinutes=x>=0?c.getInt(x):0;r.hourly=c.getDouble(c.getColumnIndexOrThrow("hourly"));x=c.getColumnIndex("type");r.type=x>=0?c.getString(x):"Ride";r.source=c.getString(c.getColumnIndexOrThrow("source"));x=c.getColumnIndex("thumb_path");r.thumbPath=x>=0&&!c.isNull(x)?c.getString(x):null;x=c.getColumnIndex("ocr_text");r.ocrText=x>=0&&!c.isNull(x)?c.getString(x):null;r.archived=c.getInt(c.getColumnIndexOrThrow("archived"))!=0;return r;}
}
