package com.chris.uberratebanner;
import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;
public class ScanActivity extends Activity{
 private static final int REQ=4101;private FrameLayout frame;private TextView result;private ImageView preview;private OfferAnalyzer analyzer;private RideDatabase db;private Bitmap current;
 @Override protected void onCreate(Bundle b){super.onCreate(b);UiKit.applySystemBars(this);analyzer=new OfferAnalyzer(this);db=new RideDatabase(this);build();}
 private void build(){frame=new FrameLayout(this);frame.setBackgroundColor(UiKit.BG);LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);UiKit.applySafeInsets(shell,0,0,0,0);frame.addView(shell,new FrameLayout.LayoutParams(-1,-1));ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(12),dp(18),dp(20));sv.addView(root);shell.addView(sv,new LinearLayout.LayoutParams(-1,0,1));shell.addView(UiKit.bottomNav(this,-1));setContentView(frame);TextView back=UiKit.text(this,"‹  Scan Image",23,true);back.setOnClickListener(v->finish());root.addView(back);root.addView(UiKit.muted(this,"Select a saved Uber ride or delivery offer. OCR runs locally.",13));LinearLayout chooser=new LinearLayout(this);chooser.setOrientation(LinearLayout.VERTICAL);chooser.setGravity(Gravity.CENTER);chooser.setPadding(dp(18),dp(22),dp(18),dp(22));chooser.setBackground(UiKit.rounded(UiKit.SURFACE,14,this));root.addView(chooser,top(18));chooser.addView(UiKit.text(this,"▣",36,false));TextView ct=UiKit.text(this,"Choose an image",17,true);ct.setGravity(Gravity.CENTER);chooser.addView(ct);TextView ch=UiKit.primaryButton(this,"Choose Image",v->choose());chooser.addView(ch,top(12));TextView ex=UiKit.secondaryButton(this,"Use Included Example",v->example());chooser.addView(ex,top(8));preview=new ImageView(this);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackground(UiKit.rounded(UiKit.SURFACE,12,this));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(330));pp.topMargin=dp(14);root.addView(preview,pp);result=UiKit.muted(this,"Choose an image to test OCR.",14);result.setPadding(dp(14),dp(14),dp(14),dp(14));result.setBackground(UiKit.rounded(UiKit.SURFACE,12,this));root.addView(result,top(12));}
 private void choose(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,REQ);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==REQ&&c==RESULT_OK&&data!=null&&data.getData()!=null)try(InputStream in=getContentResolver().openInputStream(data.getData())){scan(BitmapFactory.decodeStream(in),"Gallery");}catch(Exception e){result.setText("Could not open image.");}}
 private void example(){try(InputStream in=getAssets().open("example_offer.png")){scan(BitmapFactory.decodeStream(in),"Included Example");}catch(Exception e){result.setText("Could not load example.");}}
 private void scan(Bitmap b,String source){if(current!=null)current.recycle();current=scale(b,2200);if(current!=b)b.recycle();preview.setImageBitmap(current);result.setText("Reading image locally…");analyzer.analyze(current,new OfferAnalyzer.Callback(){public void onSuccess(OfferParser.ParsedOffer o){save(o,source);}public void onFailure(String m){result.setText(m);}});}
 private void save(OfferParser.ParsedOffer o,String source){long now=System.currentTimeMillis();RideRecord r=new RideRecord();r.createdAt=now;r.payout=o.payout;r.pickupMinutes=o.pickupMinutes;r.tripMinutes=o.tripMinutes;r.baseTotalMinutes=o.baseTotalMinutes;r.deliveryBufferMinutes=o.deliveryBufferMinutes;r.stopCount=o.stopCount;r.stopBufferMinutes=o.stopBufferMinutes;r.totalMinutes=o.totalMinutes;r.hourly=o.hourly;r.type=o.type;r.source=source;r.ocrText=o.rawText;try{r.thumbPath=ImageStorage.saveVerificationCrop(this,current,o.cropRect,now);}catch(Exception ignored){}r.id=db.insert(r);String extra="Delivery".equals(r.type)?"\nUber total "+r.baseTotalMinutes+" min + "+r.deliveryBufferMinutes+" min wait buffer":"\nPickup "+r.pickupMinutes+" min • Trip "+r.tripMinutes+" min"+(r.stopCount>0?" • "+r.stopCount+" stop"+(r.stopCount==1?"":"s")+" +"+r.stopBufferMinutes+" min":"");result.setText(String.format(Locale.US,"$%.2f/hr\n$%.2f payout • %d min total%s\n\nSaved to History.",r.hourly,r.payout,r.totalMinutes,extra));result.setTextColor(RateColors.textForHourly(this,r.hourly));result.setBackground(UiKit.outlined(UiKit.SURFACE,RateColors.forHourly(this,r.hourly),2,12,this));BannerUi.show(this,frame,r);}
 private Bitmap scale(Bitmap b,int max){int m=Math.max(b.getWidth(),b.getHeight());if(m<=max)return b;float f=max/(float)m;return Bitmap.createScaledBitmap(b,Math.round(b.getWidth()*f),Math.round(b.getHeight()*f),true);}private int dp(int v){return UiKit.dp(this,v);}private LinearLayout.LayoutParams top(int t){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(t);return p;}
 @Override protected void onDestroy(){if(current!=null)current.recycle();analyzer.close();db.close();super.onDestroy();}
}
