package com.chris.uberratebanner;
import android.app.*;import android.graphics.Color;import android.os.Bundle;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;
public class SettingsActivity extends Activity{
 private static final String[] CN={"Red","Orange","Green","Blue","Yellow","Purple","Teal","Pink","Gray","Black"};private static final int[] CV={Color.rgb(227,38,54),Color.rgb(255,140,0),Color.rgb(10,159,61),Color.rgb(25,118,210),Color.rgb(246,201,69),Color.rgb(123,31,162),Color.rgb(0,137,123),Color.rgb(216,27,96),Color.rgb(97,97,97),Color.rgb(17,17,17)};private static final String[] TN={"White","Black"};private static final int[] TV={Color.WHITE,Color.BLACK};
 private Switch auto;private EditText limit,delivery;private SeekBar duration;private TextView durationLabel,rangeDesc,bp,mp,tp;private DualRangeSlider range;private Spinner bb,bt,mb,mt,tb,tt;
 @Override protected void onCreate(Bundle b){super.onCreate(b);UiKit.applySystemBars(this);build();load();refresh();}
 private void build(){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(UiKit.BG);UiKit.applySafeInsets(shell,0,0,0,0);ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(12),dp(18),dp(28));sv.addView(root);shell.addView(sv,new LinearLayout.LayoutParams(-1,0,1));shell.addView(UiKit.bottomNav(this,2));setContentView(shell);root.addView(UiKit.text(this,"Settings",24,true));root.addView(UiKit.muted(this,"Customize retention, delivery estimate, banner timing, thresholds and colors.",12));
  LinearLayout hist=card(root,"History & storage");auto=new Switch(this);auto.setText("Auto-delete oldest rides");auto.setTextColor(UiKit.TEXT);hist.addView(auto);limit=num();hist.addView(UiKit.muted(this,"Normal history limit (1–5000)",11),top(9));hist.addView(limit,top(4));
  LinearLayout del=card(root,"Delivery calculations");del.addView(UiKit.muted(this,"Extra wait-time buffer added to Uber's displayed delivery total (0–15 min)",11));delivery=num();del.addView(delivery,top(6));
  LinearLayout timing=card(root,"Banner timing");durationLabel=UiKit.text(this,"",14,true);timing.addView(durationLabel);duration=new SeekBar(this);duration.setMax(25);duration.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){refreshDuration();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});timing.addView(duration,top(6));timing.addView(UiKit.muted(this,"Minimum 2.5 sec • Maximum 15 sec • Default 5 sec",11));
  LinearLayout ranges=card(root,"Hourly-rate ranges");rangeDesc=UiKit.text(this,"",13,true);ranges.addView(rangeDesc);range=new DualRangeSlider(this);range.setBounds(20,40);range.setListener((l,h)->refresh());ranges.addView(range,new LinearLayout.LayoutParams(-1,dp(94)));ranges.addView(UiKit.muted(this,"Range selection is $20–$40. Calculations can still fall below or above this range.",11));
  LinearLayout colors=card(root,"Banner colors");bb=spin(CN);bt=spin(TN);bp=row(colors,"Bottom Range",bb,bt,"$22.00/hr  •  $11.00  •  30 min");mb=spin(CN);mt=spin(TN);mp=row(colors,"Mid Range",mb,mt,"$25.00/hr  •  $12.50  •  30 min");tb=spin(CN);tt=spin(TN);tp=row(colors,"Top Range",tb,tt,"$30.00/hr  •  $15.00  •  30 min");
  android.widget.AdapterView.OnItemSelectedListener lis=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){refresh();}public void onNothingSelected(android.widget.AdapterView<?> p){}};for(Spinner s:new Spinner[]{bb,bt,mb,mt,tb,tt})s.setOnItemSelectedListener(lis);
  LinearLayout act=new LinearLayout(this);TextView cancel=UiKit.secondaryButton(this,"Cancel",v->finish()),save=UiKit.primaryButton(this,"Save",v->save());act.addView(cancel,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(0,-2,1);x.leftMargin=dp(8);act.addView(save,x);root.addView(act,top(18));}
 private LinearLayout card(LinearLayout r,String t){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(14),dp(15),dp(14));c.setBackground(UiKit.rounded(UiKit.SURFACE,12,this));c.addView(UiKit.text(this,t,16,true));r.addView(c,top(16));return c;}private EditText num(){EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setTextColor(UiKit.TEXT);e.setBackground(UiKit.outlined(UiKit.SURFACE_2,UiKit.DIVIDER,1,8,this));e.setPadding(dp(12),dp(10),dp(12),dp(10));return e;}
 private Spinner spin(String[] a){Spinner s=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a);s.setAdapter(ad);s.setBackground(UiKit.rounded(UiKit.SURFACE_2,8,this));return s;}private TextView row(LinearLayout root,String label,Spinner a,Spinner b,String mock){root.addView(UiKit.text(this,label,13,true),top(12));LinearLayout row=new LinearLayout(this);row.addView(a,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,-2,1);q.leftMargin=dp(8);row.addView(b,q);root.addView(row,top(4));TextView p=UiKit.text(this,mock,14,true);p.setGravity(Gravity.CENTER);root.addView(p,new LinearLayout.LayoutParams(-1,Math.max(dp(28),Math.round(getResources().getDisplayMetrics().densityDpi*.25f))));return p;}
 private void load(){auto.setChecked(AppSettings.autoDeleteEnabled(this));limit.setText(""+AppSettings.historyLimit(this));delivery.setText(""+AppSettings.deliveryWaitBuffer(this));duration.setProgress(Math.round((AppSettings.bannerDurationMs(this)-2500)/500f));range.setValues(AppSettings.lowCutoff(this),AppSettings.highCutoff(this));set(bb,AppSettings.bottomBannerColor(this),CV);set(bt,AppSettings.bottomTextColor(this),TV);set(mb,AppSettings.midBannerColor(this),CV);set(mt,AppSettings.midTextColor(this),TV);set(tb,AppSettings.topBannerColor(this),CV);set(tt,AppSettings.topTextColor(this),TV);}
 private void save(){int l,d;try{l=Integer.parseInt(limit.getText().toString());d=Integer.parseInt(delivery.getText().toString());}catch(Exception e){Toast.makeText(this,"Check numeric settings",Toast.LENGTH_SHORT).show();return;}if(l<1||l>5000||d<0||d>15){Toast.makeText(this,"History 1–5000; delivery buffer 0–15",Toast.LENGTH_LONG).show();return;}AppSettings.save(this,auto.isChecked(),l,d,range.getLowValue(),range.getHighValue(),color(bb,CV),color(bt,TV),color(mb,CV),color(mt,TV),color(tb,CV),color(tt,TV));AppSettings.setBannerDurationMs(this,2500+duration.getProgress()*500);new RideDatabase(this).enforceRetention();Toast.makeText(this,"Settings saved",Toast.LENGTH_SHORT).show();finish();}
 private void refresh(){if(rangeDesc==null)return;int l=range.getLowValue(),h=range.getHighValue();rangeDesc.setText("Bottom < $"+l+"/hr   •   Mid $"+l+"–$"+h+"/hr   •   Top > $"+h+"/hr");apply(bp,color(bb,CV),color(bt,TV));apply(mp,color(mb,CV),color(mt,TV));apply(tp,color(tb,CV),color(tt,TV));refreshDuration();}private void refreshDuration(){if(durationLabel!=null)durationLabel.setText(String.format(Locale.US,"Banner display: %.1f seconds",(2500+duration.getProgress()*500)/1000f));}private void apply(TextView v,int bg,int fg){if(v!=null){v.setBackground(UiKit.rounded(BannerUi.translucent(bg),8,this));v.setTextColor(fg);}}private int color(Spinner s,int[] v){return v[Math.max(0,Math.min(v.length-1,s.getSelectedItemPosition()))];}private void set(Spinner s,int val,int[] a){for(int i=0;i<a.length;i++)if(a[i]==val){s.setSelection(i);return;}}
 private int dp(int v){return UiKit.dp(this,v);}private LinearLayout.LayoutParams top(int t){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(t);return p;}
}
