package com.chris.uberratebanner;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.text.*;import android.text.style.RelativeSizeSpan;import android.view.*;import android.widget.*;
public final class UiKit{
 public static final int BG=Color.rgb(7,17,21),SURFACE=Color.rgb(18,31,37),SURFACE_2=Color.rgb(25,42,49),TEXT=Color.rgb(245,249,250),MUTED=Color.rgb(164,180,187),BLUE=Color.rgb(45,126,247),GREEN=Color.rgb(30,221,82),DIVIDER=Color.rgb(43,61,68); private UiKit(){}
 public static int dp(Context c,int v){return Math.round(v*c.getResources().getDisplayMetrics().density);} public static GradientDrawable rounded(int c,int r,Context x){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(x,r));return g;} public static GradientDrawable outlined(int f,int s,int sw,int r,Context c){GradientDrawable g=rounded(f,r,c);g.setStroke(dp(c,sw),s);return g;}
 public static TextView text(Context c,String s,float sp,boolean b){TextView t=new TextView(c);t.setText(s);t.setTextSize(sp);t.setTextColor(TEXT);t.setBreakStrategy(Build.VERSION.SDK_INT>=23?android.text.Layout.BREAK_STRATEGY_HIGH_QUALITY:0);if(b)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;} public static TextView muted(Context c,String s,float sp){TextView t=text(c,s,sp,false);t.setTextColor(MUTED);return t;}
 public static TextView primaryButton(Context c,String s,View.OnClickListener l){TextView b=text(c,s,16,true);b.setGravity(Gravity.CENTER);b.setPadding(dp(c,16),dp(c,15),dp(c,16),dp(c,15));b.setBackground(rounded(BLUE,10,c));b.setOnClickListener(l);return b;} public static TextView secondaryButton(Context c,String s,View.OnClickListener l){TextView b=text(c,s,15,true);b.setGravity(Gravity.CENTER);b.setPadding(dp(c,14),dp(c,14),dp(c,14),dp(c,14));b.setBackground(outlined(SURFACE_2,DIVIDER,1,10,c));b.setOnClickListener(l);return b;}
 public static TextView compactToolButton(Context c,String icon,String label,View.OnClickListener l){TextView b=text(c,"",11,true);setCompactToolLabel(b,icon,label);b.setGravity(Gravity.CENTER);b.setLineSpacing(0,0.9f);b.setMinHeight(dp(c,52));b.setPadding(dp(c,6),dp(c,5),dp(c,6),dp(c,5));b.setBackground(outlined(SURFACE_2,DIVIDER,1,9,c));b.setOnClickListener(l);return b;}
 public static void setCompactToolLabel(TextView b,String icon,String label){String s=icon+"\n"+label;SpannableString sp=new SpannableString(s);sp.setSpan(new RelativeSizeSpan(1.65f),0,icon.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);b.setText(sp);}
 public static LinearLayout actionCard(Context c,String icon,String title,String sub,View.OnClickListener l){LinearLayout card=new LinearLayout(c);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER);card.setPadding(dp(c,14),dp(c,15),dp(c,14),dp(c,14));card.setBackground(rounded(SURFACE,12,c));card.setOnClickListener(l);TextView i=text(c,icon,25,false);i.setGravity(Gravity.CENTER);card.addView(i);TextView h=text(c,title,15,true);h.setGravity(Gravity.CENTER);card.addView(h);TextView x=muted(c,sub,11);x.setGravity(Gravity.CENTER);card.addView(x);return card;}
 public static void applySafeInsets(View v,int baseL,int baseT,int baseR,int baseB){final Context c=v.getContext();final int l=dp(c,baseL),t=dp(c,baseT),r=dp(c,baseR),b=dp(c,baseB),extra=dp(c,6);v.setOnApplyWindowInsetsListener((view,in)->{int L=0,T=0,R=0,B=0;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());L=x.left;T=x.top;R=x.right;B=x.bottom;}else{L=in.getSystemWindowInsetLeft();T=in.getSystemWindowInsetTop();R=in.getSystemWindowInsetRight();B=in.getSystemWindowInsetBottom();}view.setPadding(l+L+extra,t+T+extra,r+R+extra,b+B+extra);return in;});v.requestApplyInsets();}
 public static LinearLayout bottomNav(Activity a,int selected){LinearLayout nav=new LinearLayout(a);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.setBackgroundColor(Color.rgb(9,21,26));applySafeInsets(nav,8,4,8,4);addNav(a,nav,"⌂","Home",0,selected,MainActivity.class);addNav(a,nav,"◷","History",1,selected,HistoryActivity.class);addNav(a,nav,"⚙","Settings",2,selected,SettingsActivity.class);return nav;}
 private static void addNav(Activity a,LinearLayout nav,String icon,String label,int idx,int sel,Class<?> cls){LinearLayout item=new LinearLayout(a);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);item.setPadding(dp(a,6),dp(a,3),dp(a,6),dp(a,3));item.setMinimumHeight(dp(a,54));item.setBackground(outlined(idx==sel?SURFACE_2:Color.rgb(11,25,30),idx==sel?BLUE:DIVIDER,1,10,a));TextView i=text(a,icon,23,idx==sel);i.setGravity(Gravity.CENTER);i.setTextColor(idx==sel?BLUE:MUTED);TextView l=text(a,label,11,idx==sel);l.setGravity(Gravity.CENTER);l.setTextColor(idx==sel?TEXT:MUTED);item.addView(i,new LinearLayout.LayoutParams(-1,dp(a,28)));item.addView(l,new LinearLayout.LayoutParams(-1,dp(a,18)));item.setOnClickListener(x->{if(idx==sel)return;Intent in=new Intent(a,cls);in.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);a.startActivity(in);if(!(a instanceof MainActivity))a.finish();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(a,56),1f);lp.leftMargin=dp(a,4);lp.rightMargin=dp(a,4);nav.addView(item,lp);}
 public static void applySystemBars(Activity a){a.getWindow().setStatusBarColor(BG);a.getWindow().setNavigationBarColor(BG);}
}
